/* Exporta cada uno de los archivos delimitados :D */

export * from './export/edifAdmin'
export * from './export/edifAulas'
export * from './export/biblioteca'
export * from './export/plazoleta'

export * from './export/gimnasio'
export * from './export/salonJuegos'
export * from './export/canchaVoley'
export * from './export/rotonda'

export * from './export/cafeteria_latia'
export * from './export/cafeteria'

export * from './export/parqueaderoAdm1'
export * from './export/parqueaderoAdm2'
export * from './export/parqueaderoEstu'

export * from './export/laboratorioProduccion'
export * from './export/laboratorioAnatomia'
export * from './export/laboratorioCiencias'

export * from './export/aulas/aula1-2'
export * from './export/aulas/aula3'
export * from './export/aulas/aula4'
export * from './export/aulas/aula5-6'
export * from './export/aulas/aula7-8'
export * from './export/aulas/aula9'
export * from './export/aulas/aula10'
export * from './export/aulas/aula11'
export * from './export/aulas/aula12-13'
export * from './export/aulas/aula14'
export * from './export/aulas/aula15'
export * from './export/aulas/aula16'
export * from './export/aulas/aula17'
export * from './export/aulas/aula18'
export * from './export/aulas/aula20'
export * from './export/aulas/aula21'
export * from './export/aulas/aula22'
export * from './export/aulas/aula23'
